package com.zzcm.webase.core.dao;

import java.io.Serializable;

/**
 * Created by Administrator on 2016/2/19.
 */
public interface WriteDao<T,K extends Serializable>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Thu Feb 18 18:50:27 CST 2016
     */
    int deleteByPrimaryKey(K id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Thu Feb 18 18:50:27 CST 2016
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated Thu Feb 18 18:50:27 CST 2016
     */
    int updateByPrimaryKey(T record);
}
